server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@micro-services.pcnlxzl.mongodb.net/
      database: micro-services

